name: "Build"
on:
  pull_request:
  push:
jobs:
  test-nixos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.ayles-pc.config.system.build.toplevel
    - run: nix flake check
  test-wsl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#nixosConfigurations.ayles-wsl.config.system.build.toplevel
    - run: nix flake check
  test-darwin:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - run: nix build .#darwinConfigurations.ayles-osx.config.system.build.toplevel
    - run: nix flake check
